### ISSUE TITLE
FWIW logback.xml

### ISSUE THREAD

**Issue by BeckySharp** [lum-ai/odinson#242]
These settings (or file existence?) seem to require projects that depend on them to include their own `logback.xml` to get the logging to display.

https://github.com/lum-ai/odinson/blob/89277aa9494d6d1d52cd97400f11bab32e6b21af/core/src/main/resources/logback.xml#L1

If this is intended/OK then cool, but wanted to point it out in case it was unknown.

**Comment by BeckySharp** [comment]
@kwalcock  can you please look into the way this works and/or consequences of removing it all together?

**Comment by kwalcock** [comment]
I've noticed that we're starting to get conflicts between logback.xml files, particularly in assembly, when they need to be combined in some way when their names clash.  I was wondering how easily they can be placed in project-specific directories, like ai/lum/odinson/logback.xml and ai/lum/eidosdottir/logback.xml so that they are each independent and can coexist.  Does anyone know if that would work?  Can @BeckySharp briefly described the behavior she has observed?

It seems like in general, the values in this last logback.xml might override the more global settings of other logback files (or lack of files, like the root level values) so that things are only displayed when there are more specific settings in the logback files of dependencies, which might then be required.

**Comment by BeckySharp** [comment]
ok, so the behavior I noticed is that i have odinson as a dependency in eidosdottir.  When I tried to use LazyLogging in EidosDottir, nothing was being output -- not for `info` or `debug` (didn't try `error`), and I tried in both IntelliJ and sbt run in the terminal.  
I poked at this a bit:
 - When I tried changing certain aspects of the odinson `logback.xml` (e.g., the ```additivity```) it didn't make any difference
 - When I renamed `logback.xml` to `logback.xml.BAK`, the eidosdittor statements printed to the console as expected _AND_ I noticed that it was also printing logging statements from Eidos -- i.e., when sourcing and sinking files.
 - When I added the odinson one back in, AND added a very similar `logback.xml` to eidosdottir (changed the name only), it also started printing eidosdottir statements to the console, BUT it did NOT show the Eidos logging statements.  

**I don't know** if logging statements in odinson (e.g., in the ExtractorEngine) are printing when I have a `logback.xml` in eidosdottir bc I didn't add any to check... (and I didn't check to see if there are any)

**Comment by kwalcock** [comment]
Brief :-?  I'll try to find some guidelines on how to deal with multiple, competing log files.  I worry that we are simply doing it wrong. 
 LazyLogging doesn't look immediately familiar.

**Comment by kwalcock** [comment]
I haven't forgotten about this.  http://logback.qos.ch/manual/loggingSeparation.html was noted as one of the articles to read, but the advice there didn't seem sufficient to solve the problem.  It seemed to at least attest to there being a problem.

**Comment by kwalcock** [comment]
It probably won't solve the problem, but it may help with the weirdness.  This change in the clulab version, https://github.com/clulab/eidos/pull/946, will be ported soon.

**Comment by kwalcock** [comment]
I am still looking into it.  It sounds like in the case of multiple resources of the same name, only one will be used.  If things are lazy, it may be that whoever logs first determines which file is used.  That might even differ between runs.

**Comment by kwalcock** [comment]
This is additionally complicated by the fact that eidos proper is not being used, but eidos-eidoscommon and eidos-ontologies and they do not have any logback.xml file at all.  If assembly is ever used, there would only be one logback.xml anyway, so as an experiment, I would try to combine each of the files and I'm submitting a PR for that.  If there are multiple files, it's not clear to me which of them will be used.  I hope that some experimentation and observation will clear that up rather than an investigation.

**Comment by BeckySharp** [comment]
hmmmm... ok.  is there any way to say in my logback.xml that i want all log
messages from the dependencies, regardless of which depepndency?

**Comment by kwalcock** [comment]
I don't know what the defaults are (and will look it up), but if something like
```xml
    <root level="ALL">
        <appender-ref ref="STDOUT" />
    </root>
```
is there, you'll see everything (ALL) in STDOUT, probably too much.  It might not look like the output that the individual programs would otherwise show, because the level is different, the appenders are different, the patterns are different, etc.  Some eidos timing information that was recorded to file will only show up on screen and thereafter be lost, etc. again.

Some of the Stanford code uses a different logger and this line from eidos proper rather than any of the subprojects might be useful:
```scala
  // Turn off warnings from this class.
  edu.stanford.nlp.ie.NumberNormalizer.setVerbose(false)
```

**Comment by BeckySharp** [comment]
so maybe instead of "ALL" we could set the level some other way?  or am i
barking up the wrong tree?

**Comment by kwalcock** [comment]
According to http://logback.qos.ch/manual/configuration.html, this is what you get if logback.xml is not available.  The default mode is debug, so you should get anything more important with the order being ALL TRACE DEBUG INFO WARN ERROR FATAL OFF.

```xml
<configuration>

  <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
    <!-- encoders are assigned the type
         ch.qos.logback.classic.encoder.PatternLayoutEncoder by default -->
    <encoder>
      <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
    </encoder>
  </appender>

  <root level="debug">
    <appender-ref ref="STDOUT" />
  </root>
</configuration>
```

**Comment by kwalcock** [comment]
However, I'm not accounting for com.typesafe.scalalogging.LazyLogging which may work completely differently.  Eidos tries to use logback and would like to have that logback.xml, but also includes log4j as a dependency because some libraries it uses seem IIRC not to declare any kind logging and somehow leave it up for grabs.  Also, logback (ch.qos.logback) is probably "organized" by slf4j, because code like

```scala
lazy val logger: Logger = LoggerFactory.getLogger(this.getClass)
```
is going through `import org.slf4j.{Logger, LoggerFactory}`.  It might work based on what kind of configuration files it finds.  So, it is probably a tangled mess.

**Comment by kwalcock** [comment]
But it looks like LazyLogging is meant to work with logback.  I like the configuration of the logger via the LazyLogging trait. +1.  I may add that, but then add a level of indirection, an EidosLogger which can be managed in one place.

**Comment by BeckySharp** [comment]
it certainly sounds like a tangled mess!  OK, i will then just do whatever
you tell me to do!! and i'll try this out, hopefully today, but i have to
finish something else first

**Comment by kwalcock** [comment]
clulab/eidos has a very simple `TestLogback` just to check what's going on.  Lines could be added to provoke some logging message from odinson or eidoscommon to see what happens, how it's formatted, etc.

**Comment by kwalcock** [comment]
clulab/eidos has a Logging trait in eidoscommon which is now used throughout the project.  It will eventually be available in the lum-ai version.  It's ~1 line of code, but it is good for standardization.

**Comment by kwalcock** [comment]
It *seems* like this has been cleared up.
