### ISSUE TITLE
Data consistency issue  in backend API search results and the stored documents.

### ISSUE THREAD

**Issue by curtkohler** [lum-ai/odinson#336]
**Describe the bug**
Data consistency issue  in backend API search results and the stored documents.

We have been using our own internal parsing engine(with custom tokenization rules),  formatting the results into Odinson JSON documents, and then loading them into an Odinson index.  While everything works well for the most part, occasionally I've been seeing match spans that appear to be off by one or two. I initially assumed an edge case issue in my code, but digging deeper I think there is a conflict between backend and core. After looking at things in more detail, it became apparent that extra tokens are being generated in the query response's "words" field in at least the execute/pattern API call. As I mentioned, we have a custom tokenization which allows for embedded whitespace in some tokens. These tokens (along with some other cases) appear to be getting split when generating the API response for a query. The api's sentence call results show the index contains the un-split tokens. It also appears that the match offsets returned in the query response align correctly with the un-split tokenization as well.

I believe that the Lucene analyser is being applied to the already parsed tokens when the OdinsonController calls the core's DataGatherer.getTokens() call - which is further spliting things.  That seems odd given that you are already dealing with pre-tokenized fields, but it my be necessary for some other aspect of the code base I haven't looked at.

I'm attaching an example scoreDoc entry from a  query result as well as the corresponding sentence request output. You can see that the token. 'Figure 3' becomes two separate tokens in the query response each time it appears in the sentence.

**Expected behavior**
I would expect Odinson backend API to respect the tokenization of the loaded docs and not re-define it.

[ExampleSentenceResponse.txt](https://github.com/lum-ai/odinson/files/7076936/ExampleSentenceResponse.txt)
[ExampleQueryResponse.txt](https://github.com/lum-ai/odinson/files/7076937/ExampleQueryResponse.txt)

**Comment by myedibleenso** [comment]
Hi, @curtkohler .  Thank you for reporting this.  We'll dig in.  Just to confirm: the sentence in `ExampleSentenceResponse.txt` has the ID 5035?

**Comment by curtkohler** [comment]
Yes, that was returned by the API call:  http://XX.XX.XX.XX:8001/api/sentence?sentenceId=5035. Happy to provide the entire original JSON document that was indexed if needed, but I suspect just creating a test JSON doc with the one sentence (less the two additional fields we've added) would be enough to work with.  Also, there are a couple of other Figure references in that particular sentence that we treat as a single token that are getting split up as well.

**Comment by danebell** [comment]
Hi, @curtkohler. Odinson's [`IndexWriter`](https://github.com/lum-ai/odinson/blob/992cb0cfff5472bc14728da510530f32310238fc/core/src/main/scala/ai/lum/odinson/OdinsonIndexWriter.scala#L44) currently uses lucene's [`WhitespaceAnalyzer`](https://lucene.apache.org/core/6_6_6//analyzers-common/org/apache/lucene/analysis/core/WhitespaceAnalyzer.html), which will break any tokens on whitespace, as the name suggests. Currently, the choice of `Analyzer` isn't configurable. A possible workaround is to extend `IndexWriter`, overriding the value of `writerConfig` such that it uses [`KeywordAnalyzer`](https://lucene.apache.org/core/6_6_6//analyzers-common/org/apache/lucene/analysis/core/KeywordAnalyzer.html) instead, which preserves whitespace:

```
import org.apache.lucene.analysis.core.KeywordAnalyzer
import org.apache.lucene.store.Directory
import ai.lum.odinson.digraph.Vocabulary
import ai.lum.odinson.utils.IndexSettings
import ai.lum.odinson.OdinsonIndexWriter

class KeywordOdinsonIndexWriter(
  override val directory: Directory,
  override val vocabulary: Vocabulary,
  override val settings: IndexSettings,
  override val normalizedTokenField: String,
  override val addToNormalizedField: Set[String],
  override val incomingTokenField: String,
  override val outgoingTokenField: String,
  override val maxNumberOfTokensPerSentence: Int,
  override val invalidCharacterReplacement: String,
  override val displayField: String
) extends OdinsonIndexWriter(
  directory,
  vocabulary,
  settings,
  normalizedTokenField,
  addToNormalizedField,
  incomingTokenField,
  outgoingTokenField,
  maxNumberOfTokensPerSentence,
  invalidCharacterReplacement,
  displayField
) {
  val kwAnalyzer = new KeywordAnalyzer()
  override val writerConfig = new IndexWriterConfig(kwAnalyzer)
}
```

The reason why retrieving the sentence with `api/sentence` still preserves your custom tokenization is that that endpoint loads your original input JSON from disk rather than loading it from the index, in case there were fields in the input that weren't stored in the index.

**Comment by curtkohler** [comment]
Dane, Thanks for the quick reply and suggestion on a workaround.  A couple of observations. I guess would have expected Odinson to leverage the Lucene Keyword Analyzer by default since the input documents are already tokenized. It seems counter-intuitive that the system re-tokenizes previously tokenized content. It is also odd that the match offsets being returned in the API's JSON query response reflect the original source document tokenization strategy and not what was apparently put into the index based on your reply. In my simple query UI, had I made an extra API call to the /sentence endpoint and generated the display from that, the highlighting would have been correct.

**Comment by danebell** [comment]
@BeckySharp The lucene `IndexWriter` needs a `IndexWriterConfig`, which will have some `Analyzer` in any case (`StandardAnalyzer` if none is specified IIRC). I'm not as familiar with `DataGatherer` -- would it be possible to make the choice of `Analyzer` configurable? Would an `Analyzer` that keeps things as-is cause problems?

@curtkohler I believe you're right that the `KeywordAnalyzer` would be more appropriate. Unless I hear otherwise, I'll begin a pull request to make it so.

**Comment by BeckySharp** [comment]
@danebell I think you can swap it in the DG no problem, but unit tests will tell us for sure.

One thing though @curtkohler the **metadata** query language won't support the spaces within the tokens, so you'd have to come up with a workaround there.  Again, that's only for the metadata queries.

**Comment by curtkohler** [comment]
@BeckySharp - Yes, I would expect the metadata query capability to continue to use one of the other Lucene tokenizers as it doesn't appear to be designed to handle pre-tokenized data (things like title, author names, etc.) and that isn't a problem for us.

**Comment by BeckySharp** [comment]
Actually, they should be tokenized, but whitespace within a token isn't supported (last I checked, a test could be added).
see, e.g.,:
- https://github.com/lum-ai/odinson/blob/master/core/src/test/scala/ai/lum/odinson/metadata/TestMetadataFilter.scala#L44
- #329

**Comment by BeckySharp** [comment]
@danebell has this been worked on?  what needs to be done?

**Comment by danebell** [comment]
I believe this has now been fully addressed. See [this pull request](https://github.com/lum-ai/odinson/pull/337), since merged.
