### ISSUE TITLE
Remove `backend` subproject from Odinson

### ISSUE THREAD

**Issue by danebell** [lum-ai/odinson#356]
Migrate the `backend` subproject to its own repo, namely [`odinson-backend`](https://github.com/lum-ai/odinson-backend).

- [x] create `odinson-backend`
- [ ] migrate [subproject contents](https://github.com/lum-ai/odinson/tree/f025cd6ca13f5c93bb5c08f4c507802ba1a199d4/backend)
- [ ] migrate [docker ci](https://github.com/lum-ai/odinson/blob/f025cd6ca13f5c93bb5c08f4c507802ba1a199d4/.github/workflows/docker.yml#L83-L89)

**Comment by reynoldsm88** [comment]
@danebell when you complete this task let me know, i'd be interested to see the impact on the code coverage report for `odinson`. i'd like to update the coverage to be more complete, but a significant portion of that drop was related to `backend` tests that i ignored because i was having problems with `play`/`guice`

**Comment by danebell** [comment]
@reynoldsm88 Will do! Thanks for keeping up.

**Comment by myedibleenso** [comment]
closed via https://github.com/lum-ai/odinson/pull/357
